Add app group support for iOS
margelo/react-native-nitro-sqlite pull request #8
Opened 2023-06-23 16:37 UTC by ryanlntn

This adds app group support for iOS configurable via adding an `AppGroup` key to `Info.plist` allowing sharing data between process in the same app group (e.g. with a share extension).

This is the simplest solution but I outline some ways it could potentially be made more robust [here](https://github.com/margelo/react-native-quick-sqlite/issues/6). I'm happy to work on including anything from that outline as well should it seem useful.

2023-07-11 19:39 UTC, chrispader commented
This LGTM!

Still going to check with the other maintainers tomorrow, if we want to go for the `Info.plist` approach on configuration. Personally, i don't think it's a problem, so should be fine.

Thanks for the PR! 🚀🥳

2023-07-11 19:42 UTC, chrispader approved these changes
LGTM! 🥳

2023-07-11 20:29 UTC, chrispader requested changes

2023-07-11 20:29 UTC, chrispader commented on ios/QuickSQLite.mm
> +    documentPath = [storeUrl path];
Please add this to prevent problems when installing the library with an invalid app group ID defined in `Info.plist`:

```objective-c
NSURL *storeUrl = [fileManager containerURLForSecurityApplicationGroupIdentifier:appGroupID];

// ADD THIS
if (storeUrl == nil) {
    NSLog(@"Invalid AppGroup ID provided (%@). Check the value of \"AppGroup\" in your Info.plist file", appGroupID);
    return @false;
}

NSLog(@"Configured with AppGroup ID: %@", appGroupID);
// END ADD

documentPath = [storeUrl path];
```

2023-07-11 20:30 UTC, chrispader requested changes
only one small change requested :)

2023-07-11 21:05 UTC, ryanlntn commented on ios/QuickSQLite.mm
> +    documentPath = [storeUrl path];
Good call! 😄

2023-07-12 06:16 UTC, chrispader approved these changes
Thanks, looks great!

2023-07-12 10:15 UTC, merged